### ISSUE TITLE
[Feature Request] Apple Cash parallax animated image for other cards

### ISSUE THREAD

**Issue by Void48** [leminlimez/Cowabunga#101]
It should be possible to move all the files that make up the animated parallax image to other Apple Wallet card folders and then maybe somehow get the same animated card image as Apple Cash? Just look in the files

**Comment by BomberFish** [comment]
This could be possible, further investigation is needed.

**Comment by bank5ia** [comment]
[Sydney](https://chariz.com/buy/sydney) developer here:

I have pretty decent knowledge of the inner-working of the wallet app and how all the files work and good luck trying to do this. If I remember correctly, the passbook app verifies the files associated with each card. Using a parallax effect would require multiple files to be placed within the card's folder. I have a feeling that the verification wouldn't allow for extra files, let alone the modification of the pass's information to actually use a parallax effect instead of it's default image.

**Comment by BomberFish** [comment]
@bank5ia Thank you so much for your insight!

**Comment by leminlimez** [comment]
> [Sydney](https://chariz.com/buy/sydney) developer here:
> 
> I have pretty decent knowledge of the inner-working of the wallet app and how all the files work and good luck trying to do this. If I remember correctly, the passbook app verifies the files associated with each card. Using a parallax effect would require multiple files to be placed within the card's folder. I have a feeling that the verification wouldn't allow for extra files, let alone the modification of the pass's information to actually use a parallax effect instead of it's default image.

Through experimentation, I was only able to replace card images with pngs successfully but I also do not have much experience looking through how it works. I do not think it verifies for the card images itself though, otherwise replacing the image probably wouldn't have been possible in the first place

**Comment by leminlimez** [comment]
not possible to do without jailbreak
