### ISSUE TITLE
My phone is stuck in a boot loop after dying after changes

### ISSUE THREAD

**Issue by dogestech** [leminlimez/Cowabunga#173]
Bro

**Comment by leminlimez** [comment]
what tweaks did you have enabled?

**Comment by dogestech** [comment]
custom carrier name, custom time

**Comment by dogestech** [comment]
now i have to restore in itunes

**Comment by dogestech** [comment]
thanks a lot

**Comment by leminlimez** [comment]
You do not have to be aggressive about it. I will definitely add a warning to the status bar since if it screws up, it does not revert on reboot. I am so sorry this happened, but you may want to create an issue at StatusMagic since he is the original creator of the feature: https://github.com/Avangelista/StatusMagic

**Comment by leminlimez** [comment]
Could I also get your device model and ios version prior to the bootloop?

**Comment by dogestech** [comment]
iOS 15.0, iPhone 6s Plus and iOS 15.5, iPhone SE (1st gen)

**Comment by dogestech** [comment]
New version: iOS 15.7.3, iPhone 6s Plus and iPhone SE (Not fixed yet)

**Comment by dogestech** [comment]
And I installed it with Scarlet on both devices

**Comment by GTREBLA** [comment]
You sure? I have custom carrier for a week in XS 15.4.1 using TrollStore and using custom carrier for 3 weeks on 14PM using AltStore... i tried custom time too. Anyways custom carrier dont modify any important file, right? Is like passcode themes or dial phone themes?
