### ISSUE TITLE
Delete shortcut banners problem

### ISSUE THREAD

**Issue by TrueAsura** [leminlimez/Cowabunga#174]
After tapping ‘delete’ the shortcuts app redirects, I tried restarting phone i tried respringing and enabling reduce motion from settings but nothing. Before i never had a redirect but now I have a 2-4 second redirect which is annoying. For now I recommend no one use that feature.
Iphone SE 2020 ios:16.0.3

EDIT: for me to fix this problem i had to redo all shortcuts from scratch again.

**Comment by leminlimez** [comment]
Are you sure it is not from the AppClips?

**Comment by TrueAsura** [comment]
> Are you sure it is not from the AppClips?

I only clicked delete shortcut banners then the problem occurred so I didn’t click anything else.

**Comment by LegacyDev99** [comment]
I can confirm this issue also occurs on iOS 16.1.  iOS 16 introduced special banners for Shortcuts that aren't actual banners, so the handling of WebClips was likely changed at the same time.

When the ShortcutIdentifier key is missing from the WebClip Info.plist on iOS 16, SpringBoard opens the Shortcuts app to run the shortcut instead of showing the banner at the top of the screen.

Maybe using an invalid or blank ShortcutIdentifier would cause SpringBoard to behave differently, but that's just a guess.
I do not have an easy way to test this due to SantanderEscaped not having write access to the WebClips directory.

**Comment by leminlimez** [comment]
This could very well be the case. I can add back the previous method that worked only on ios 16

**Comment by LegacyDev99** [comment]
I was able to test the ShortcutIdentifier key, and if an invalid or blank key is set, the WebClip does nothing when tapped.

Could you add an option to restore the ShortcutIdentifier key? The value can be recovered from the URL key.
On iOS 16 it looks like:
shortcuts://x-callback-url/run-shortcut?name=TheNameOfTheShortcut&id=00000000-0000-0000-0000-000000000000&source=homescreen

**Comment by LegacyDev99** [comment]
Unless I have missed something, this does not appear to be resolved in the latest release (v8.1.3).
Has this been resolved in an unreleased beta?

To summarize, this issue requested the following changes:

- Restore the previous Shortcuts banner hide method that worked only on iOS 16
- Add an option to undo the "Delete Shortcut Banners" operation by restoring the ShortcutIdentifier key by using the RegEx `[?&]id=([^?&#]*)` on the URL key
