### ISSUE TITLE
Almost nothing works

### ISSUE THREAD

**Issue by KeyFlyz** [leminlimez/Cowabunga#190]
iPad Pro M1 IOS 15.6.1 fonts don't work theming don't work as a matter of fact the only thing that does work is applying a passcode face, hide dock and that's about it at this point you might as well scrape the app because the developers have no idea what there doing it's ridiculous! And the only reason I would even use this app is for fonts and theming so it's useless!

**Comment by KeyFlyz** [comment]
I can't believe they even have a Patreon link for a app that doesn't even work guess there looking for free money for nothing lol

**Comment by cassafrass387** [comment]
> the only reason I would even use this app is for fonts and theming
Use WDBFontOverwrite for fonts, it does a better job and I think the Cowabunga devs would plainly admit this. As for theming, in what way does setting icon themes not work? Like is there any kind of error message, are you following all the steps correctly, et cetera. As for the Patreon, for one thing if the app didn’t work no one would subscribe to the Patreon, and without that Patreon lemin and the other developers would be making this software project for free. Everyone who doesn’t subscribe to the Patreon still gets new builds, just a bit later than everyone else (but less buggy since they’ve been beta tested). Of course it’s going to have bugs, it’s utilizing an underdocumented exploit which is unreliable at best. Not their fault that they have to work within the limitations of it.
On a side note, if you have trouble with setting other themeing settings, like the Dock or App Library blur, try using this method to respring:
https://reddit.com/r/jailbreak/comments/107pr7w/tutorial_app_library_respring_method_for_ios_16/
It yields better odds of getting the tweaks to apply.

**Comment by leminlimez** [comment]
> I can't believe they even have a Patreon link for a app that doesn't even work guess there looking for free money for nothing lol

We do this out of passion and do not ask for much back. The patreon is only to support us, you are in no way required or expected to subscribe to it. The app works for most people. We cannot diagnose every issue on every device within a reasonable amount of time. The app itself is free, so if you don't like it then don't use it. I will not help you if you continue to be rude to me or the other developers.

Try the app library method like what @cassafrass387 said, as others said that it helps applying consistency. I have tried multiple in-app respring methods but none have a consistent result other than app library respringing.

**Comment by potteredgerton** [comment]
if you don't like it don't use it. the developers of this app have put many hours into it, but they work for free so there are going to be bugs.

**Comment by sorae42** [comment]
The app works on my phone, so boo-hoo.
