### ISSUE TITLE
[Cool Feature Request] Video Wallpaper

### ISSUE THREAD

**Issue by Lucidyty** [leminlimez/Cowabunga#256]
Having the option to set a video as a wallpaper similar to how Eneko or Frame worked would be incredible!

**Comment by sorae42** [comment]
impossible

**Comment by TropicLegend** [comment]
Why is it impossible to get a video/live/animated wallpaper?

**Comment by leminlimez** [comment]
not possible, requires tweak injection or an on device exploit

**Comment by sorae42** [comment]
> Why is it impossible to get a video/live/animated wallpaper?

you can get the live wallpaper on iOS right now (the one where it animates when you hold down the screen)

video wallpaper isn't possible because apple's implementation of wallpaper doesn't allow video playback. Tweaks like Eneko implement a video player on top of iOS wallpaper to display video wallpaper (you can still see your original wallpaper when you edit your lockscreen)

**Comment by leminlimez** [comment]
live wallpaper was removed in ios 16, it does not work anymore
