### ISSUE TITLE
Jailbreak vs Jailed Exploit

### ISSUE THREAD

**Issue by Radiicall** [leminlimez/Cowabunga#43]
This question is kind of dumb but do you think you could explain what the difference between a jailed exploit and a normal jailbreak is?

**Comment by TherionRO** [comment]
A jailed exploit will modify system files using a bug that is present in iOS,without patching the kernel or making any other changes,just changing a few files in the system.

A jailbreak on the other hand will give you almost full acces on your iDevice,you can modify,change all the things you want because your ios is patched by the jailbreak tool you used.The jailed exploit doesnt patch your system to give you admin rights,it writes already existing ios files like assets or sounds.

**Comment by Radiicall** [comment]
So this can't be used in any way to achieve a jailbreak?

**Comment by TherionRO** [comment]
> So this can't be used in any way to achieve a jailbreak?

No,because you cant really patch system files using this exploit. I tried patching some system files with this exploit but the system will just crash and bootloop.But this exploit will surely help and improve the jailbreak chances for affected ios versions.

I really want a jailbreak for my iphones but sadly non of them are jailbreakable,what iPhone and ios version do you got?

**Comment by Radiicall** [comment]
iPhone 13 Pro on iOS 16.0.

This is my first iOS device in a while, my last one was a 6s and jailbreaking was always the best part.

**Comment by TherionRO** [comment]
> iPhone 13 Pro on iOS 16.0.
> 
> This is my first iOS device in a while, my last one was a 6s and jailbreaking was always the best part.

Uh oh,sorry to say this but your device cant be jailbroken as of yet. 13 pro max can only be jailbroken up to 15.1.1 using xinaA15 jailbreak. Atleast you can use some of the jailed tweaks with this exploit.Just think about it,what if this explot never got published? When a jailbreak will come to ios 16 for A12+ devices the internet will go crazy.It didnt happened with xina because it was too late,maybe we will be lucky this year with 16.

**Comment by Radiicall** [comment]
Yeah I have looked at xinaa15 before, I wish I left my phone on the iOS version it came with, 15.0 or something similar... Anyways, thanks for your input
